name: cv
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  custom_sliding_segmented_control: ^1.8.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
