name: cv_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  buttons_tabbar: ^1.3.8
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  http: ^1.1.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
